## Sorteo Estudiantes

Generación de Equipos de trabajos para presentación de temas

In [2]:
import pandas as pd
lista_path = 'ICCD332_GR1CC_2024-2CalificacionesB1-2Upload.xlsx'
sheet_name = "Calificaciones"
student_df = pd.read_excel(lista_path, sheet_name=sheet_name)
student_df.shape

(29, 30)

In [4]:
student_df_new = student_df.copy()
# student_df_new = student_df[-student_df["Prueba"].isna()]

In [5]:
student_df_new.shape

(29, 30)

In [6]:
import numpy as np
result_dict = {}
team_labels = ['E1', 'Q1', 'E2','Q2', 'E3', 'Q3', 'E4', 'Q4']
weeks = ['W1', 'W2', 'W3', 'W4', 'W5']
for r, w in enumerate(weeks):
    df = student_df_new.sample(frac=1).reset_index(drop=True)
    df[w] = ""
    num_teams = len(team_labels)
    for i, row in enumerate(df.iterrows()):
        team_idx = i%num_teams
        df.at[row[0], w] = team_labels[team_idx]
    result_dict[w] = df

In [8]:
lista_dataframes  = []
for key in result_dict.keys():
    this_dict = dict(zip(result_dict[key]['Dirección de correo'], result_dict[key][key]))
    this_df = pd.DataFrame(this_dict.items(), columns=['Dirección de correo', key])
    lista_dataframes.append(this_df)

In [9]:
result_df = student_df_new.copy()
for other_df in lista_dataframes:
    result_df = pd.merge(result_df, other_df, on="Dirección de correo", how='inner')
result_df.shape

(29, 35)

In [10]:
result_df

,Nombre,Apellido(s),Número de ID,Institución,Departamento,Dirección de correo,Foro:Rating grade for The hardware Lottery (Real),Tarea:The Hardware Lottery (Real),Foro:Whole forum grade for The hardware Lottery (Real),Tarea:Representación de Enteros con Signo (Real),...,Total Prueba-B1 (Real),Total PrimerBimestre (Real),Tarea:Revisar nota primer Bimestre (Real),Última descarga de este curso,Column1,W1,W2,W3,W4,W5
0,LENIN ALEXANDER,AMANGANDI LLUMIGUANO,NaN,NaN,NaN,lenin.amangandi@epn.edu.ec,-,7.0,7.5,9.44,...,16.70,17.25,OK,1734019161,*,Q3,E3,E3,E2,E4
1,JAIRO ANDRES,ANGULO YANDUN,NaN,NaN,NaN,jairo.angulo@epn.edu.ec,-,9.0,10.0,9.72,...,17.70,18.36,OK,1734019161,*,E2,E1,E1,E4,E2
2,TAMARA JUDITH,BENAVIDEZ SALAZAR,NaN,NaN,NaN,tamara.benavidez@epn.edu.ec,-,9.0,10.0,8.47,...,15.00,17.41,OK,1734019161,*,E2,E4,Q4,Q3,E3
3,CAMILA DANIELA,CAICEDO ALCIVAR,NaN,NaN,NaN,camila.caicedo@epn.edu.ec,-,10.0,2.5,8.75,...,14.25,16.16,OK,1734019161,*,Q3,E3,Q3,Q2,E1
4,MAURICIO ALEJANDRO,CARRION AVILES,NaN,NaN,NaN,mauricio.carrion@epn.edu.ec,-,8.0,5.0,9.72,...,14.00,16.66,OK,1734019161,*,E4,Q1,Q3,E1,Q4
5,MATTHEW ISRAEL,CEDEÑO DIAZ,NaN,NaN,NaN,matthew.cedeno@epn.edu.ec,-,9.0,0.0,9.58,...,14.25,15.94,OK,1734019161,*,Q3,Q3,E4,Q4,E2
6,SEBASTIAN ALEJANDRO,CHICAIZA CHICAIZA,NaN,NaN,NaN,sebastian.chicaiza@epn.edu.ec,-,8.0,0.0,7.08,...,18.40,16.66,OK,1734019161,*,E2,Q4,Q1,Q3,Q3
7,DAVID ALEJANDRO,CUASQUER RODRIGUEZ,NaN,NaN,NaN,david.cuasquer@epn.edu.ec,-,9.0,5.0,9.16,...,9.50,15.39,OK,1734019161,*,Q2,Q1,Q1,E2,E2
8,JUAN MARTIN,CUSME CARRERA,NaN,NaN,NaN,juan.cusme@epn.edu.ec,-,10.0,7.5,8.40,...,20.00,18.73,OK,1734019161,*,Q4,E2,E2,Q4,Q3
9,ANGEL DIEGO,FALCON JACOME,NaN,NaN,NaN,angel.falcon@epn.edu.ec,-,10.0,7.5,9.16,...,13.00,17.28,OK,1734019161,*,E3,E2,E3,E2,Q4
10,MARIA CELESTE,GALLARDO MORENO,NaN,NaN,NaN,maria.gallardo01@epn.edu.ec,-,8.0,0.0,8.40,...,16.05,16.78,OK,1734019161,*,E2,E2,E3,E4,Q1
11,KEVIN EDUARDO,GARCIA RODRIGUEZ,NaN,NaN,NaN,kevin.garcia01@epn.edu.ec,-,9.0,5.0,7.29,...,20.00,18.09,OK,1734019161,*,Q1,Q2,Q1,Q2,E4
12,ANDERSON JOEL,HERRERA PANCHI,NaN,NaN,NaN,anderson.herrera@epn.edu.ec,-,10.0,10.0,9.72,...,14.40,17.78,OK,1734019161,*,E4,E4,E2,Q1,E1
13,ELIZABETH LORENA,LOPEZ ZELAYA,NaN,NaN,NaN,elizabeth.lopez@epn.edu.ec,-,10.0,10.0,9.44,...,13.50,16.91,OK,1734019161,*,E1,E1,E1,E1,E3
14,MARCO ALEJANDRO,MARCILLO MOLINA,NaN,NaN,NaN,marco.marcillo@epn.edu.ec,-,7.5,7.5,8.75,...,15.20,15.14,OK,1734019161,*,Q2,Q4,Q1,Q1,Q3
15,JOSHUA DANIEL,MENENDEZ FARIAS,NaN,NaN,NaN,joshua.menendez@epn.edu.ec,-,10.0,0.0,9.16,...,11.00,14.98,OK,1734019161,*,E3,Q2,E1,E3,Q2
16,PRESLY DAVID,MORALES VELASTEGUI,NaN,NaN,NaN,presly.morales@epn.edu.ec,-,9.0,7.5,9.16,...,18.00,16.83,OK,1734019161,*,Q1,E1,E2,Q2,Q1
17,FRANCISCO DAVID,MORALES ZALDUMBIDE,NaN,NaN,NaN,francisco.morales01@epn.edu.ec,-,10.0,10.0,9.44,...,17.10,18.56,OK,1734019161,*,E1,Q3,E1,E3,E1
18,JUAN PABLO,MURILLO TOBAR,NaN,NaN,NaN,juan.murillo@epn.edu.ec,-,8.0,5.0,8.88,...,17.00,17.19,OK,1734019161,*,E3,E4,E4,E3,Q4
19,SEBASTIAN DANILO,PAZMIÑO SALAZAR,NaN,NaN,NaN,sebastian.pazmino@epn.edu.ec,-,9.0,0.0,4.00,...,13.00,13.93,OK,1734019161,*,Q1,E1,E2,Q2,E4
20,JUAN FRANCISCO,PINTO ANDRANGO,NaN,Escuela Politécnica Nacional,NaN,juan.pinto@epn.edu.ec,-,8.0,7.5,7.36,...,17.00,17.57,OK,1734019161,*,Q4,Q2,E3,E3,E1
21,FELIPE ANTONIO,QUIROLA SOTOMAYOR,NaN,NaN,NaN,felipe.quirola@epn.edu.ec,-,9.0,7.5,7.08,...,12.75,16.25,OK,1734019161,*,E3,E3,E4,Q1,Q1
22,BYRON EDUARDO,SALAZAR ROBAYO,NaN,NaN,NaN,byron.salazar01@epn.edu.ec,-,10.0,10.0,9.44,...,20.00,19.84,OK,1734019161,*,Q2,Q4,Q3,E1,Q2
23,JOSE ARMANDO,SARANGO CUENCA,NaN,NaN,NaN,jose.sarango@epn.edu.ec,-,10.0,10.0,7.84,...,15.75,17.69,OK,1734019161,*,Q2,E2,Q4,Q3,E3
24,JOSUNE ANTONELLA,SINGAÑA TAPIA,NaN,NaN,NaN,josune.singana@epn.edu.ec,-,10.0,10.0,10.00,...,19.26,18.62,OK,1734019161,*,Q4,Q1,Q2,E2,Q1
25,JOEL STALIN,TINITANA CARRION,NaN,NaN,NaN,joel.tinitana@epn.edu.ec,-,8.0,10.0,7.84,...,15.90,17.25,OK,1734019161,*,Q1,Q3,Q4,Q1,E3
26,DANNY PAUL,TIPAN AMAGUA,NaN,NaN,NaN,danny.tipan@epn.edu.ec,-,10.0,7.5,9.44,...,18.50,18.84,OK,1734019161,*,E4,E3,Q2,Q4,Q2
27,RICHARD ANDERSON,TIPANTIZA CUASCOTA,NaN,NaN,NaN,richard.tipantiza@epn.edu.ec,-,8.0,10.0,9.44,...,14.20,17.18,OK,1734019161,*,E1,Q2,Q2,E1,Q2
28,JESUA STEVEN,VILLACIS ALCARRAZ,NaN,NaN,NaN,jesua.villacis@epn.edu.ec,-,8.0,0.0,9.44,...,18.00,16.44,OK,1734019161,*,E1,Q1,Q2,E4,E2

In [11]:
result_df.W5.value_counts()

W5
E2    4
E3    4
E1    4
Q1    4
Q2    4
E4    3
Q4    3
Q3    3
Name: count, dtype: int64

In [13]:
result_df.to_excel('EstudiantsShuff.xlsx', index=False)

In [16]:
temp_df = pd.read_excel('EstudiantsShuff.xlsx')
temp_df.shape

(29, 35)

In [17]:
def total_expo(*args):
    cont_expo = 0
    for col in args:
        if 'E' in  col:
            cont_expo+=1
    return cont_expo

def total_quest(*args):
    cont_quest = 0
    for col in args:
        if 'Q' in  col:
            cont_quest+=1
    return cont_quest

temp_df['Total_E'] = temp_df.apply(lambda x: total_expo(x['W1'], x['W2'], x['W3'], x['W4'], x['W5']), axis=1)
temp_df['Total_Q'] = temp_df.apply(lambda x: total_quest(x['W1'], x['W2'], x['W3'], x['W4'], x['W5']), axis=1)

In [18]:
temp_df

,Nombre,Apellido(s),Número de ID,Institución,Departamento,Dirección de correo,Foro:Rating grade for The hardware Lottery (Real),Tarea:The Hardware Lottery (Real),Foro:Whole forum grade for The hardware Lottery (Real),Tarea:Representación de Enteros con Signo (Real),...,Tarea:Revisar nota primer Bimestre (Real),Última descarga de este curso,Column1,W1,W2,W3,W4,W5,Total_E,Total_Q
0,LENIN ALEXANDER,AMANGANDI LLUMIGUANO,NaN,NaN,NaN,lenin.amangandi@epn.edu.ec,-,7.0,7.5,9.44,...,OK,1734019161,*,Q3,E3,E3,E2,E4,4,1
1,JAIRO ANDRES,ANGULO YANDUN,NaN,NaN,NaN,jairo.angulo@epn.edu.ec,-,9.0,10.0,9.72,...,OK,1734019161,*,E2,E1,E1,E4,E2,5,0
2,TAMARA JUDITH,BENAVIDEZ SALAZAR,NaN,NaN,NaN,tamara.benavidez@epn.edu.ec,-,9.0,10.0,8.47,...,OK,1734019161,*,E2,E4,Q4,Q3,E3,3,2
3,CAMILA DANIELA,CAICEDO ALCIVAR,NaN,NaN,NaN,camila.caicedo@epn.edu.ec,-,10.0,2.5,8.75,...,OK,1734019161,*,Q3,E3,Q3,Q2,E1,2,3
4,MAURICIO ALEJANDRO,CARRION AVILES,NaN,NaN,NaN,mauricio.carrion@epn.edu.ec,-,8.0,5.0,9.72,...,OK,1734019161,*,E4,Q1,Q3,E1,Q4,2,3
5,MATTHEW ISRAEL,CEDEÑO DIAZ,NaN,NaN,NaN,matthew.cedeno@epn.edu.ec,-,9.0,0.0,9.58,...,OK,1734019161,*,Q3,Q3,E4,Q4,E2,2,3
6,SEBASTIAN ALEJANDRO,CHICAIZA CHICAIZA,NaN,NaN,NaN,sebastian.chicaiza@epn.edu.ec,-,8.0,0.0,7.08,...,OK,1734019161,*,E2,Q4,Q1,Q3,Q3,1,4
7,DAVID ALEJANDRO,CUASQUER RODRIGUEZ,NaN,NaN,NaN,david.cuasquer@epn.edu.ec,-,9.0,5.0,9.16,...,OK,1734019161,*,Q2,Q1,Q1,E2,E2,2,3
8,JUAN MARTIN,CUSME CARRERA,NaN,NaN,NaN,juan.cusme@epn.edu.ec,-,10.0,7.5,8.40,...,OK,1734019161,*,Q4,E2,E2,Q4,Q3,2,3
9,ANGEL DIEGO,FALCON JACOME,NaN,NaN,NaN,angel.falcon@epn.edu.ec,-,10.0,7.5,9.16,...,OK,1734019161,*,E3,E2,E3,E2,Q4,4,1
10,MARIA CELESTE,GALLARDO MORENO,NaN,NaN,NaN,maria.gallardo01@epn.edu.ec,-,8.0,0.0,8.40,...,OK,1734019161,*,E2,E2,E3,E4,Q1,4,1
11,KEVIN EDUARDO,GARCIA RODRIGUEZ,NaN,NaN,NaN,kevin.garcia01@epn.edu.ec,-,9.0,5.0,7.29,...,OK,1734019161,*,Q1,Q2,Q1,Q2,E4,1,4
12,ANDERSON JOEL,HERRERA PANCHI,NaN,NaN,NaN,anderson.herrera@epn.edu.ec,-,10.0,10.0,9.72,...,OK,1734019161,*,E4,E4,E2,Q1,E1,4,1
13,ELIZABETH LORENA,LOPEZ ZELAYA,NaN,NaN,NaN,elizabeth.lopez@epn.edu.ec,-,10.0,10.0,9.44,...,OK,1734019161,*,E1,E1,E1,E1,E3,5,0
14,MARCO ALEJANDRO,MARCILLO MOLINA,NaN,NaN,NaN,marco.marcillo@epn.edu.ec,-,7.5,7.5,8.75,...,OK,1734019161,*,Q2,Q4,Q1,Q1,Q3,0,5
15,JOSHUA DANIEL,MENENDEZ FARIAS,NaN,NaN,NaN,joshua.menendez@epn.edu.ec,-,10.0,0.0,9.16,...,OK,1734019161,*,E3,Q2,E1,E3,Q2,3,2
16,PRESLY DAVID,MORALES VELASTEGUI,NaN,NaN,NaN,presly.morales@epn.edu.ec,-,9.0,7.5,9.16,...,OK,1734019161,*,Q1,E1,E2,Q2,Q1,2,3
17,FRANCISCO DAVID,MORALES ZALDUMBIDE,NaN,NaN,NaN,francisco.morales01@epn.edu.ec,-,10.0,10.0,9.44,...,OK,1734019161,*,E1,Q3,E1,E3,E1,4,1
18,JUAN PABLO,MURILLO TOBAR,NaN,NaN,NaN,juan.murillo@epn.edu.ec,-,8.0,5.0,8.88,...,OK,1734019161,*,E3,E4,E4,E3,Q4,4,1
19,SEBASTIAN DANILO,PAZMIÑO SALAZAR,NaN,NaN,NaN,sebastian.pazmino@epn.edu.ec,-,9.0,0.0,4.00,...,OK,1734019161,*,Q1,E1,E2,Q2,E4,3,2
20,JUAN FRANCISCO,PINTO ANDRANGO,NaN,Escuela Politécnica Nacional,NaN,juan.pinto@epn.edu.ec,-,8.0,7.5,7.36,...,OK,1734019161,*,Q4,Q2,E3,E3,E1,3,2
21,FELIPE ANTONIO,QUIROLA SOTOMAYOR,NaN,NaN,NaN,felipe.quirola@epn.edu.ec,-,9.0,7.5,7.08,...,OK,1734019161,*,E3,E3,E4,Q1,Q1,3,2
22,BYRON EDUARDO,SALAZAR ROBAYO,NaN,NaN,NaN,byron.salazar01@epn.edu.ec,-,10.0,10.0,9.44,...,OK,1734019161,*,Q2,Q4,Q3,E1,Q2,1,4
23,JOSE ARMANDO,SARANGO CUENCA,NaN,NaN,NaN,jose.sarango@epn.edu.ec,-,10.0,10.0,7.84,...,OK,1734019161,*,Q2,E2,Q4,Q3,E3,2,3
24,JOSUNE ANTONELLA,SINGAÑA TAPIA,NaN,NaN,NaN,josune.singana@epn.edu.ec,-,10.0,10.0,10.00,...,OK,1734019161,*,Q4,Q1,Q2,E2,Q1,1,4
25,JOEL STALIN,TINITANA CARRION,NaN,NaN,NaN,joel.tinitana@epn.edu.ec,-,8.0,10.0,7.84,...,OK,1734019161,*,Q1,Q3,Q4,Q1,E3,1,4
26,DANNY PAUL,TIPAN AMAGUA,NaN,NaN,NaN,danny.tipan@epn.edu.ec,-,10.0,7.5,9.44,...,OK,1734019161,*,E4,E3,Q2,Q4,Q2,2,3
27,RICHARD ANDERSON,TIPANTIZA CUASCOTA,NaN,NaN,NaN,richard.tipantiza@epn.edu.ec,-,8.0,10.0,9.44,...,OK,1734019161,*,E1,Q2,Q2,E1,Q2,2,3
28,JESUA STEVEN,VILLACIS ALCARRAZ,NaN,NaN,NaN,jesua.villacis@epn.edu.ec,-,8.0,0.0,9.44,...,OK,1734019161,*,E1,Q1,Q2,E4,E2,3,2

In [20]:
temp_df.groupby(['Total_E', 'Total_Q'])['Dirección de correo'].count().reset_index()

   Total_E  Total_Q  Dirección de correo
0        0        5                    1
1        1        4                    5
2        2        3                    9
3        3        2                    6
4        4        1                    6
5        5        0                    2

In [21]:
temp_df.to_excel('shuffletmp.xlsx', index=False)